# .pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: check-ast
  - id: check-json
  - id: check-yaml
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: requirements-txt-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.1
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/PyCQA/autoflake
  rev: v2.3.1
  hooks:
  - id: autoflake
    args: [--remove-all-unused-imports, "--remove-duplicate-keys", "--remove-unused-variables", --in-place]
